services: 
 - docker
 
language: java
script: ant run

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "serglazk" -p "zaq12wsx";
    docker build -f Dockerfile -t serglazk/my_repository .;
    docker push serglazk/my_repository;
    fi
